use clap::{Parser, Subcommand};

/// Simple Rust CLI harness for AI code generation and autonomous agentic workflow.
#[derive(Parser, Debug, Clone)]
#[command(name = "ctrl-cli")]
#[command(author = "Generated by Antigravity")]
#[command(version = env!("CARGO_PKG_VERSION"))]
#[command(about = "Ultra-lightweight AI Coding Agent with CLI and TUI modes", long_about = None)]
pub struct Cli {
    /// Launch in classic line-based CLI / REPL mode instead of modern TUI.
    #[arg(long)]
    pub cli: bool,

    /// Explicitly launch the modern Terminal User Interface (TUI).
    #[arg(short = 't', long)]
    pub tui: bool,

    /// Launch embedded local web dashboard in background while running REPL or TUI.
    #[arg(long)]
    pub web: bool,

    #[command(subcommand)]
    pub command: Option<Commands>,
}

#[derive(Subcommand, Debug, Clone)]
pub enum Commands {
    /// Launch modern interactive Terminal User Interface (TUI).
    Tui,

    /// Launch classic line-based interactive REPL.
    Repl,

    /// Launch embedded local HTTP server for visual monitoring dashboard.
    Serve {
        /// Port to bind the server (default: 3000).
        #[arg(short, long, default_value_t = 3000)]
        port: u16,

        /// Host interface to bind (default: 127.0.0.1).
        #[arg(short = 'H', long, default_value = "127.0.0.1")]
        host: String,
    },

    /// Generate code or complete an agentic task from a prompt.
    Generate {
        /// Model name override (e.g. glm-5.3-flash, deepseek-chat, gpt-4o-mini).
        #[arg(short, long)]
        model: Option<String>,

        /// Skill to activate for generation (e.g. rust-expert, code-reviewer, web-frontend).
        #[arg(short, long)]
        skill: Option<String>,

        /// Show token usage and context window metrics.
        #[arg(short = 't', long)]
        tokens: bool,

        /// Save generated code directly to file instead of printing to terminal.
        #[arg(short, long)]
        output: Option<String>,

        /// Prompt to send to the AI code generation provider.
        #[arg(num_args = 1.., required = true)]
        prompt: Vec<String>,
    },
}

pub fn default_true() -> bool {
    true
}
