mod agent;
mod tools;
mod types;

use agent::memory::MemoryManager;
use agent::orchestrator::run_agent_loop;
use agent::permissions::{PermissionGate, PermissionMode};
use anyhow::Result;
use clap::{Parser, Subcommand};
use inquire::autocompletion::{Autocomplete, Replacement};
use inquire::error::CustomUserError;
use inquire::{InquireError, Select, Text};
use serde::{Deserialize, Serialize};
use std::io::{IsTerminal, Write};
use std::path::PathBuf;
use types::{ChatMessage, Usage};

/// Simple Rust CLI harness for AI code generation and autonomous agentic workflow.
#[derive(Parser)]
#[command(name = "ctrl-cli")]
#[command(author = "Generated by Antigravity")]
#[command(version = "0.2.0")]
#[command(about = "Ultra-lightweight AI Coding Agent CLI with tool execution", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate code or complete an agentic task from a prompt.
    Generate {
        /// Model name override (e.g. glm-5.3-flash, deepseek-chat, gpt-4o-mini).
        #[arg(short, long)]
        model: Option<String>,

        /// Skill to activate for generation (e.g. rust-expert, code-reviewer, web-frontend).
        #[arg(short, long)]
        skill: Option<String>,

        /// Show token usage and context window metrics.
        #[arg(short = 't', long)]
        tokens: bool,

        /// Save generated code directly to file instead of printing to terminal.
        #[arg(short, long)]
        output: Option<String>,

        /// Prompt to send to the AI code generation provider.
        #[arg(num_args = 1.., required = true)]
        prompt: Vec<String>,
    },
}

fn default_true() -> bool {
    true
}

#[derive(Serialize, Deserialize, Clone, Debug)]
struct UserProfile {
    name: String,
    tech_stack: Vec<String>,
    response_language: String,
    coding_style: String,
    #[serde(default = "default_true")]
    show_token_usage: bool,
}

impl Default for UserProfile {
    fn default() -> Self {
        Self {
            name: "galangfjr".to_string(),
            tech_stack: vec![
                "Python".to_string(),
                "TypeScript".to_string(),
                "Rust".to_string(),
                "Zig".to_string(),
            ],
            response_language: "Bahasa Indonesia".to_string(),
            coding_style: "Tulis kode yang bersih (clean code), modern, idiomatik, efisien, dan minim dependensi tidak perlu. Berikan penjelasan ringkas dan solutif.".to_string(),
            show_token_usage: true,
        }
    }
}

fn load_user_profile() -> UserProfile {
    let home = std::env::var_os("USERPROFILE")
        .or_else(|| std::env::var_os("HOME"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    let profile_dir = home.join(".ctrl-cli");
    let profile_path = profile_dir.join("profile.json");

    if profile_path.exists() {
        if let Ok(data) = std::fs::read_to_string(&profile_path) {
            if let Ok(prof) = serde_json::from_str::<UserProfile>(&data) {
                return prof;
            }
        }
    }

    let default_profile = UserProfile::default();
    if std::fs::create_dir_all(&profile_dir).is_ok() {
        if let Ok(json_str) = serde_json::to_string_pretty(&default_profile) {
            let _ = std::fs::write(&profile_path, json_str);
        }
    }
    default_profile
}

fn save_user_profile(profile: &UserProfile) {
    let home = std::env::var_os("USERPROFILE")
        .or_else(|| std::env::var_os("HOME"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    let profile_dir = home.join(".ctrl-cli");
    let profile_path = profile_dir.join("profile.json");

    if std::fs::create_dir_all(&profile_dir).is_ok() {
        if let Ok(json_str) = serde_json::to_string_pretty(profile) {
            let _ = std::fs::write(&profile_path, json_str);
        }
    }
}

#[derive(Clone)]
struct Skill {
    id: &'static str,
    name: &'static str,
    description: &'static str,
    system_prompt: &'static str,
}

fn get_available_skills() -> Vec<Skill> {
    vec![
        Skill {
            id: "rust-expert",
            name: "🦀 Rust Expert",
            description: "Spesialis Rust idiomatik, borrow checker, & performa tinggi",
            system_prompt: "You are an elite Rust systems programming expert. Write idiomatic, memory-safe, and high-performance Rust code. Master the borrow checker, use zero-cost abstractions, prefer Result/Option error handling, and explain safety invariants clearly.",
        },
        Skill {
            id: "code-reviewer",
            name: "🔍 Code Reviewer",
            description: "Audit kode menyeluruh untuk bug, celah keamanan, & code smells",
            system_prompt: "You are a senior principal engineer and code reviewer. Rigorously review code for logical bugs, potential memory leaks, security vulnerabilities, edge cases, and maintainability issues. Provide constructive feedback with corrected, refactored code.",
        },
        Skill {
            id: "web-frontend",
            name: "🎨 Web Frontend UI/UX",
            description: "Desain antarmuka modern, HTML/CSS/Tailwind responsif & estetik",
            system_prompt: "You are a modern frontend architect and UI/UX designer. Create visually aesthetic, accessible, modern, and responsive user interfaces using modern HTML, CSS, Tailwind, or component frameworks with clean layouts.",
        },
        Skill {
            id: "api-architect",
            name: "🏗️ API & Backend Architect",
            description: "Desain REST/GraphQL API, skema database, dan autentikasi",
            system_prompt: "You are an enterprise backend and API architect. Design clean, scalable, RESTful or GraphQL APIs with robust validation, secure authentication (JWT/OAuth), clear error response schemas, and efficient database modeling.",
        },
        Skill {
            id: "security-auditor",
            name: "🛡️ Security Auditor",
            description: "Audit keamanan aplikasi (OWASP Top 10, sanitasi input, mitigasi exploit)",
            system_prompt: "You are an application security specialist. Identify security vulnerabilities adhering to OWASP Top 10 guidelines (e.g. injection, broken auth, XSS, SSRF). Explain attack vectors and provide hardened, secure code patches.",
        },
        Skill {
            id: "debugger",
            name: "🐞 Debugger & Trace Doctor",
            description: "Analisis error, stack trace, dan pemecahan masalah sistematis",
            system_prompt: "You are a master software debugger. Analyze stack traces, runtime errors, and unexpected behavior systematically. Perform root-cause analysis, explain why the bug happens, and provide the exact minimal fix.",
        },
        Skill {
            id: "test-engineer",
            name: "🧪 Test Engineer & TDD",
            description: "Pembuatan unit test, integration test, mock, dan edge cases",
            system_prompt: "You are a test-driven development (TDD) engineer. Write comprehensive unit and integration test suites covering edge cases, boundary conditions, error paths, and mocks to ensure 100% reliability.",
        },
        Skill {
            id: "refactor",
            name: "🧹 Clean Code & Refactoring",
            description: "Pembersihan kode, prinsip SOLID/DRY, dan arsitektur modular",
            system_prompt: "You are a software craftsperson focused on clean code, SOLID principles, and DRY architecture. Refactor tangled or bloated code into elegant, modular, and readable components without breaking functionality.",
        },
    ]
}

#[derive(Clone, Debug)]
struct ModelContextInfo {
    context_window: u64,
    max_output: Option<u64>,
    note: &'static str,
}

fn get_model_context_info(model: &str) -> ModelContextInfo {
    let lower = model.to_lowercase();
    if lower.contains("claude-3-5-sonnet") || lower.contains("claude-3.5-sonnet") {
        ModelContextInfo {
            context_window: 200_000,
            max_output: Some(8_192),
            note: "Anthropic Claude 3.5 Sonnet (200k context)",
        }
    } else if lower.contains("gemini-1.5-pro") || lower.contains("gemini-2.0") || lower.contains("gemini-1.5-flash") {
        ModelContextInfo {
            context_window: 1_000_000,
            max_output: Some(8_192),
            note: "Google Gemini (1M context)",
        }
    } else if lower.contains("deepseek-reasoner") {
        ModelContextInfo {
            context_window: 64_000,
            max_output: Some(8_192),
            note: "DeepSeek R1 Reasoner (64k context)",
        }
    } else if lower.contains("deepseek-chat") || lower.contains("deepseek-v3") {
        ModelContextInfo {
            context_window: 64_000,
            max_output: Some(8_192),
            note: "DeepSeek V3 (64k context)",
        }
    } else if lower.contains("glm-5") || lower.contains("glm-4") {
        ModelContextInfo {
            context_window: 128_000,
            max_output: Some(4_096),
            note: "Zhipu / OpenAgentic GLM (128k context)",
        }
    } else if lower.contains("llama-3.3") || lower.contains("llama-3.1") {
        ModelContextInfo {
            context_window: 128_000,
            max_output: Some(8_192),
            note: "Meta Llama 3 (128k context)",
        }
    } else if lower.contains("qwen-2.5-coder") {
        ModelContextInfo {
            context_window: 128_000,
            max_output: Some(8_192),
            note: "Qwen 2.5 Coder (128k context)",
        }
    } else if lower.contains("gpt-4o-mini") || lower.contains("gpt-4o") {
        ModelContextInfo {
            context_window: 128_000,
            max_output: Some(16_384),
            note: "OpenAI GPT-4o (128k context, 16k output)",
        }
    } else if lower.contains("gpt-4-turbo") {
        ModelContextInfo {
            context_window: 128_000,
            max_output: Some(4_096),
            note: "OpenAI GPT-4 Turbo (128k context)",
        }
    } else if lower.contains("gpt-3.5-turbo") {
        ModelContextInfo {
            context_window: 16_385,
            max_output: Some(4_096),
            note: "OpenAI GPT-3.5 Turbo (16k context)",
        }
    } else {
        ModelContextInfo {
            context_window: 128_000,
            max_output: None,
            note: "Standard LLM (estimasi 128k context)",
        }
    }
}

#[derive(Clone, Debug, Default)]
struct SessionTokenTracker {
    total_prompt_tokens: u64,
    total_completion_tokens: u64,
    total_tokens: u64,
    query_count: u64,
    last_usage: Option<Usage>,
    last_model: Option<String>,
    last_content: Option<String>,
}

impl SessionTokenTracker {
    fn record(&mut self, usage: Option<&Usage>, model: &str, content: &str) {
        self.query_count += 1;
        self.last_model = Some(model.to_string());
        self.last_content = Some(content.to_string());
        if let Some(u) = usage {
            let p = u.prompt_tokens.unwrap_or(0);
            let c = u.completion_tokens.unwrap_or(0);
            let t = u.total_tokens.unwrap_or(p + c);
            self.total_prompt_tokens += p;
            self.total_completion_tokens += c;
            self.total_tokens += t;
            self.last_usage = Some(u.clone());
        }
    }
}

fn extract_code_block(text: &str) -> String {
    if let Some(start_idx) = text.find("```") {
        let after_fence = &text[start_idx + 3..];
        let code_start = after_fence.find('\n').map(|n| n + 1).unwrap_or(0);
        let code_body = &after_fence[code_start..];
        if let Some(end_idx) = code_body.find("```") {
            return code_body[..end_idx].to_string();
        }
    }
    text.to_string()
}

fn detect_filename(text: &str) -> Option<String> {
    let extensions = [
        ".html", ".htm", ".rs", ".py", ".ts", ".js", ".css", ".json",
        ".toml", ".yaml", ".yml", ".md", ".sh", ".sql", ".zig", ".go", ".c", ".cpp",
    ];

    for line in text.lines() {
        let trimmed = line.trim();
        let mut rest = trimmed;
        while let Some(start) = rest.find('`') {
            let after = &rest[start + 1..];
            if let Some(end) = after.find('`') {
                let candidate = after[..end].trim();
                if !candidate.contains(' ') && candidate.len() <= 50 && candidate.len() >= 3 {
                    if extensions.iter().any(|ext| candidate.ends_with(ext)) {
                        return Some(candidate.to_string());
                    }
                }
                rest = &after[end + 1..];
            } else {
                break;
            }
        }
        let mut rest_bold = trimmed;
        while let Some(start) = rest_bold.find("**") {
            let after = &rest_bold[start + 2..];
            if let Some(end) = after.find("**") {
                let candidate = after[..end].trim();
                if !candidate.contains(' ') && candidate.len() <= 50 && candidate.len() >= 3 {
                    if extensions.iter().any(|ext| candidate.ends_with(ext)) {
                        return Some(candidate.to_string());
                    }
                }
                rest_bold = &after[end + 2..];
            } else {
                break;
            }
        }
    }
    None
}

fn save_code_to_file(path_str: &str, content: &str) -> Result<String> {
    let path = std::path::Path::new(path_str);
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    let code = extract_code_block(content);
    std::fs::write(path, code.as_bytes())?;
    let line_count = code.lines().count();
    let bytes = code.len();
    Ok(format!("{} ({} baris, {} byte)", path_str, line_count, bytes))
}

fn auto_save_if_code_generated(prompt: &str, final_content: &str, tools_executed: usize) -> Option<String> {
    if tools_executed > 0 {
        return None;
    }
    let code = extract_code_block(final_content);
    if code.lines().count() >= 3 && code != final_content {
        let suggested = detect_filename(final_content)
            .or_else(|| detect_filename(prompt))
            .or_else(|| {
                let lower_p = prompt.to_lowercase();
                if lower_p.contains("html") || lower_p.contains("web") || code.contains("<!DOCTYPE") || code.contains("<html") {
                    Some("index.html".to_string())
                } else if lower_p.contains("python") || code.contains("def ") || code.contains("import sys") {
                    Some("main.py".to_string())
                } else if lower_p.contains("rust") || code.contains("fn main") {
                    Some("main.rs".to_string())
                } else {
                    None
                }
            });

        if let Some(fname) = suggested {
            if let Ok(summary) = save_code_to_file(&fname, &code) {
                let _ = MemoryManager::save_long_term_memory("append", &format!("Created file '{}'", fname));
                return Some(format!("💾 [Auto-Writer Memory] Mendeteksi kode untuk '{}'. File otomatis disimpan: {}\n", fname, summary));
            }
        }
    }
    None
}

fn format_number(n: u64) -> String {
    let s = n.to_string();
    let mut result = String::new();
    let len = s.len();
    for (i, ch) in s.chars().enumerate() {
        if i > 0 && (len - i) % 3 == 0 {
            result.push(',');
        }
        result.push(ch);
    }
    result
}

fn format_token_badge(usage: Option<&Usage>, model: &str) -> String {
    let ctx_info = get_model_context_info(model);
    if let Some(u) = usage {
        let p = u.prompt_tokens.unwrap_or(0);
        let c = u.completion_tokens.unwrap_or(0);
        let t = u.total_tokens.unwrap_or(p + c);
        let pct = if ctx_info.context_window > 0 {
            (p as f64 / ctx_info.context_window as f64) * 100.0
        } else {
            0.0
        };
        let ctx_label = if ctx_info.context_window >= 1_000_000 {
            format!("{}M", ctx_info.context_window / 1_000_000)
        } else if ctx_info.context_window >= 1_000 {
            format!("{}k", ctx_info.context_window / 1_000)
        } else {
            format!("{}", ctx_info.context_window)
        };
        format!(
            "📊 [Tokens: {} in + {} out = {} total | Context: {:.2}% of {}]",
            format_number(p),
            format_number(c),
            format_number(t),
            pct,
            ctx_label
        )
    } else {
        format!(
            "📊 [Model: {} | Context Window: {}]",
            model, ctx_info.note
        )
    }
}

fn print_token_stats(tracker: &SessionTokenTracker, current_model: &str, show_badge: bool) {
    let ctx_info = get_model_context_info(current_model);
    println!("\n══════════════════════════════════════════════════════════════");
    println!(" 📊 Token Usage & Context Window Statistics");
    println!("══════════════════════════════════════════════════════════════");
    println!(" 🤖 Model Context Window:");
    println!("  • Active Model     : {}", current_model);
    println!("  • Profile/Family   : {}", ctx_info.note);
    println!("  • Context Capacity : {} tokens", format_number(ctx_info.context_window));
    if let Some(max_out) = ctx_info.max_output {
        println!("  • Max Output Limit : {} tokens", format_number(max_out));
    }

    println!("\n ⏱️ Last Query Usage:");
    if let Some(last_u) = &tracker.last_usage {
        let p = last_u.prompt_tokens.unwrap_or(0);
        let c = last_u.completion_tokens.unwrap_or(0);
        let t = last_u.total_tokens.unwrap_or(p + c);
        let pct = if ctx_info.context_window > 0 {
            (p as f64 / ctx_info.context_window as f64) * 100.0
        } else {
            0.0
        };
        let remaining = ctx_info.context_window.saturating_sub(p);
        println!("  • Prompt (Input)   : {} tokens ({:.2}% context window terpakai)", format_number(p), pct);
        println!("  • Completion (Out) : {} tokens", format_number(c));
        println!("  • Total Last Query : {} tokens", format_number(t));
        println!("  • Sisa Ruang Bebas : {} tokens", format_number(remaining));
    } else {
        println!("  • Belum ada query yang dieksekusi di sesi ini.");
    }

    println!("\n 📈 Cumulative Session Usage:");
    println!("  • Total Queries    : {}", tracker.query_count);
    println!("  • Total Prompt     : {} tokens", format_number(tracker.total_prompt_tokens));
    println!("  • Total Completion : {} tokens", format_number(tracker.total_completion_tokens));
    println!("  • Grand Total      : {} tokens", format_number(tracker.total_tokens));
    println!("  • Auto-badge Footer: {}", if show_badge { "Aktif (ganti: `/tokens toggle`)" } else { "Nonaktif (ganti: `/tokens toggle`)" });
    println!("══════════════════════════════════════════════════════════════\n");
}

fn build_system_prompt(active_skill: Option<&Skill>, user_profile: &UserProfile) -> String {
    let base_identity = "\
Identity and context:
- You are ctrl-cli, an ultra-lightweight, high-performance autonomous coding agent CLI.
- Work inside the user's real local workspace and use it as the source of truth for code, configuration, and verification.
- You have built-in tool access: `read_file`, `write_file`, `edit_file`, `glob_files`, `grep_files`, `shell`, `read_tool_result`, `ask_user_question`, `manage_memory`, and `skill`.
- Before answering questions about the workspace, gather local evidence with tools (read_file, glob_files, grep_files). Do not guess or assume.
- When asked to build, edit, or fix something, inspect relevant files first, then use `write_file` or `edit_file`. Prefer `edit_file` for targeted surgical modifications.
- CRITICAL FILE-CREATION RULE: When the user asks to create, make, build, generate, or write a file, webpage, or script (e.g. 'create a file html', 'make me a simple html web', 'buat file'), you MUST invoke the `write_file` tool directly to save the code to the workspace. NEVER merely output markdown code blocks and instruct the user to save it themselves!
- If a tool or command fails, diagnose the error before retrying.
- Keep answers practical and concise. Do not narrate routine steps unnecessarily.";

    let skill_part = active_skill.map(|s| s.system_prompt).unwrap_or("");

    let profile_part = format!(
        "\n\n[User Profile: {}]\n- Preferred Tech Stack: {}\n- Response Language: {}\n- Coding Style Guidelines: {}",
        user_profile.name,
        user_profile.tech_stack.join(", "),
        user_profile.response_language,
        user_profile.coding_style
    );

    let memory_part = if let Some(mem) = MemoryManager::load_long_term_memory() {
        format!("\n\n[Workspace Persistent Memory (.ctrl/MEMORY.md)]:\n{}", mem)
    } else {
        String::new()
    };

    format!("{}\n\n{}{}{}", base_identity, skill_part, profile_part, memory_part)
}

#[derive(Clone, Default)]
struct SlashCompleter;

impl Autocomplete for SlashCompleter {
    fn get_suggestions(&mut self, input: &str) -> Result<Vec<String>, CustomUserError> {
        let mut suggestions = Vec::new();
        if input.starts_with("/model ") {
            let prefix = &input["/model ".len()..];
            let models = [
                "glm-5.3-flash",
                "glm-4-plus",
                "deepseek-chat",
                "deepseek-reasoner",
                "llama-3.3-70b-versatile",
                "qwen-2.5-coder-32b",
                "gpt-4o-mini",
                "gpt-4o",
                "anthropic/claude-3.5-sonnet",
            ];
            for m in models {
                if m.to_lowercase().starts_with(&prefix.to_lowercase()) {
                    suggestions.push(format!("/model {}", m));
                }
            }
        } else if input.starts_with("/skill ") {
            let prefix = &input["/skill ".len()..];
            let mut skill_ids: Vec<&str> = get_available_skills().iter().map(|s| s.id).collect();
            skill_ids.push("reset");
            for id in skill_ids {
                if id.to_lowercase().starts_with(&prefix.to_lowercase()) {
                    suggestions.push(format!("/skill {}", id));
                }
            }
        } else if input.starts_with('/') {
            let commands = [
                "/tools",
                "/permissions",
                "/memory",
                "/tokens",
                "/tokens toggle",
                "/usage",
                "/context",
                "/reset",
                "/save",
                "/write",
                "/model",
                "/skill",
                "/dev",
                "/profile",
                "/info",
                "/clear",
                "/help",
                "/exit",
            ];
            for cmd in commands {
                if cmd.starts_with(input) {
                    suggestions.push(cmd.to_string());
                }
            }
        }
        Ok(suggestions)
    }

    fn get_completion(
        &mut self,
        _input: &str,
        highlighted_suggestion: Option<String>,
    ) -> Result<Replacement, CustomUserError> {
        Ok(Replacement::Some(highlighted_suggestion.unwrap_or_default()))
    }
}

fn main() -> Result<()> {
    load_env_file();
    let mut profile = load_user_profile();
    let cli = Cli::parse();

    match cli.command {
        Some(Commands::Generate { model, skill, tokens, output, prompt }) => {
            let full_prompt = prompt.join(" ");
            let skill_obj = skill.and_then(|s_name| {
                get_available_skills()
                    .into_iter()
                    .find(|s| s.id.eq_ignore_ascii_case(&s_name))
            });
            handle_generate(&full_prompt, model.as_deref(), skill_obj.as_ref(), &profile, tokens, output.as_deref())?;
        }
        None => {
            start_repl(&mut profile)?;
        }
    }
    Ok(())
}

fn load_env_file() {
    let mut candidates = Vec::new();
    if let Ok(curr) = std::env::current_dir() {
        candidates.push(curr.join(".env"));
    }
    candidates.push(PathBuf::from(r"C:\Users\Administrator\code-agent-rust\ctrl-cli\.env"));

    for candidate in candidates {
        if candidate.exists() {
            if let Ok(content) = std::fs::read_to_string(&candidate) {
                for line in content.lines() {
                    let trimmed = line.trim();
                    if trimmed.is_empty() || trimmed.starts_with('#') {
                        continue;
                    }
                    if let Some((k, v)) = trimmed.split_once('=') {
                        let key = k.trim();
                        let mut val = v.trim();
                        if (val.starts_with('"') && val.ends_with('"'))
                            || (val.starts_with('\'') && val.ends_with('\''))
                        {
                            if val.len() >= 2 {
                                val = &val[1..val.len() - 1];
                            }
                        }
                        if std::env::var(key).is_err() {
                            std::env::set_var(key, val);
                        }
                    }
                }
            }
            break;
        }
    }
}

fn get_config() -> Result<(String, String, String)> {
    let api_key = std::env::var("AI_API_KEY").unwrap_or_default();
    if api_key.is_empty() || api_key == "your_api_key_here" {
        anyhow::bail!(
            "AI_API_KEY is not set!\n\
             Please add your API key in either:\n  \
             • File: C:\\Users\\Administrator\\code-agent-rust\\ctrl-cli\\.env\n  \
             • Terminal: $env:AI_API_KEY=\"your_api_key_here\""
        );
    }
    let base_url = std::env::var("AI_BASE_URL")
        .unwrap_or_else(|_| "https://api.openai.com/v1".to_string());
    let model = std::env::var("AI_MODEL")
        .unwrap_or_else(|_| "gpt-4o-mini".to_string());
    Ok((api_key, base_url, model))
}

fn handle_generate(
    prompt: &str,
    model_override: Option<&str>,
    active_skill: Option<&Skill>,
    user_profile: &UserProfile,
    show_tokens: bool,
    output_file: Option<&str>,
) -> Result<()> {
    let (api_key, base_url, default_model) = get_config()?;
    let model = model_override.unwrap_or(&default_model);
    let system_prompt = build_system_prompt(active_skill, user_profile);

    let mut conversation = Vec::new();
    let mut permission_gate = PermissionGate {
        mode: PermissionMode::AutoApprove,
    };

    let result = run_agent_loop(
        prompt,
        &mut conversation,
        model,
        &api_key,
        &base_url,
        &mut permission_gate,
        &system_prompt,
        25,
    )?;

    if let Some(dest) = output_file {
        match save_code_to_file(dest, &result.final_content) {
            Ok(summary) => println!("✔ File berhasil dibuat: {}", summary),
            Err(e) => {
                eprintln!("Gagal menulis file {}: {}", dest, e);
                println!("{}", result.final_content);
            }
        }
    } else {
        println!("{}", result.final_content);
        if let Some(note) = auto_save_if_code_generated(prompt, &result.final_content, result.tools_executed) {
            println!("{}", note);
        }
    }

    if show_tokens {
        println!("\n{}", format_token_badge(Some(&result.total_usage), model));
    }
    Ok(())
}

fn handle_slash_command(
    input: &str,
    current_model: &mut String,
    active_skill: &mut Option<Skill>,
    user_profile: &mut UserProfile,
    base_url: &str,
    tracker: &SessionTokenTracker,
    permission_gate: &mut PermissionGate,
    conversation: &mut Vec<ChatMessage>,
) -> bool {
    let trimmed = input.trim();
    if trimmed == "/" {
        let options = vec![
            "/tools       - Daftar built-in agent tools (read, write, edit, shell, dll.)",
            "/permissions - Pengaturan izin keamanan (Ask / AutoApprove / ReadOnly)",
            "/memory      - Lihat catatan memori proyek (.ctrl/MEMORY.md)",
            "/reset       - Reset riwayat percakapan & memori sesi (mulai konteks baru)",
            "/tokens      - Cek statistik token & context window",
            "/save        - Simpan kode respon terakhir ke file",
            "/model       - Ganti model AI aktif (pilih dari daftar)",
            "/skill       - Pilih / ganti Skill spesialis AI",
            "/dev         - Tentang pembuat / pengembang (galangfjr)",
            "/profile     - Lihat Developer Profile aktif",
            "/info        - Cek konfigurasi endpoint, context & model",
            "/clear       - Bersihkan layar terminal",
            "/help        - Tampilkan bantuan perintah",
            "/exit        - Keluar dari REPL",
        ];
        match Select::new("Pilih perintah [/]:", options).prompt() {
            Ok(choice) => {
                let cmd = choice.split_whitespace().next().unwrap_or("");
                return handle_slash_command(cmd, current_model, active_skill, user_profile, base_url, tracker, permission_gate, conversation);
            }
            _ => return true,
        }
    }

    let parts: Vec<&str> = trimmed.split_whitespace().collect();
    let cmd = parts[0].to_lowercase();

    match cmd.as_str() {
        "/help" => {
            println!("\nAvailable Slash Commands:");
            println!("  /                   - Buka menu interaktif (panah ↑/↓)");
            println!("  /tools              - Lihat daftar built-in tools yang bisa dipanggil agent");
            println!("  /permissions        - Atur kebijakan izin tool (Ask / AutoApprove / ReadOnly)");
            println!("  /memory             - Lihat catatan memori proyek (.ctrl/MEMORY.md)");
            println!("  /reset              - Kosongkan riwayat percakapan & memori sesi (fresh start)");
            println!("  /tokens, /usage     - Cek penggunaan token & limit context window");
            println!("  /tokens toggle      - Aktifkan/nonaktifkan badge token otomatis");
            println!("  /save [nama_file]   - Simpan kode respon terakhir langsung ke file");
            println!("  /model              - Pilih model dari menu daftar (panah ↑/↓)");
            println!("  /model <name>       - Ganti langsung ke model tertentu");
            println!("  /skill              - Lihat daftar & pilih skill spesialis (panah ↑/↓)");
            println!("  /skill <name>       - Aktifkan skill tertentu (misal: /skill rust-expert)");
            println!("  /skill reset        - Nonaktifkan skill (kembali ke General Assistant)");
            println!("  /dev                - Info pembuat / pengembang aplikasi ({})", user_profile.name);
            println!("  /profile            - Lihat Developer Profile Anda ({})", user_profile.name);
            println!("  /info, /config      - Tampilkan endpoint & konfigurasi sesi");
            println!("  /clear              - Bersihkan layar");
            println!("  /exit, /quit        - Keluar dari REPL");
            println!("  /help               - Bantuan ini\n");
            true
        }
        "/tools" => {
            println!("\n══════════════════════════════════════════════════════════════");
            println!(" 🛠️  Built-in Autonomous Agent Tools (Inspirasi: fx)");
            println!("══════════════════════════════════════════════════════════════");
            let tool_list = [
                ("read_file", "Membaca konten berkas dengan range baris (start_line, end_line)", "Safe (Auto)"),
                ("write_file", "Menulis berkas baru atau menimpa berkas yang ada", "Mutating (Prompt)"),
                ("edit_file", "Mengganti potongan kode eksak (target -> replacement)", "Mutating (Prompt)"),
                ("glob_files", "Mencari path berkas berdasarkan pola wildcard (*.rs, dll.)", "Safe (Auto)"),
                ("grep_files", "Mencari teks literal di seluruh berkas proyek dengan line number", "Safe (Auto)"),
                ("shell", "Mengeksekusi perintah terminal (stdout, stderr, exit code)", "Mutating (Prompt)"),
                ("read_tool_result", "Membaca potongan berikutnya dari hasil tool yang sangat panjang", "Safe (Auto)"),
                ("ask_user_question", "Bertanya interaktif ke pengguna jika butuh klarifikasi", "Interactive"),
                ("skill", "Memuat instruksi dari file SKILL.md lokal", "Safe (Auto)"),
            ];
            for (t_name, t_desc, t_pol) in tool_list {
                println!(" • {:18} [{:17}] : {}", t_name, t_pol, t_desc);
            }
            println!("══════════════════════════════════════════════════════════════\n");
            true
        }
        "/permissions" | "/security" => {
            let current_str = match permission_gate.mode {
                PermissionMode::Ask => "Ask (Minta persetujuan sebelum modifikasi berkas/shell)",
                PermissionMode::AutoApprove => "AutoApprove (Otomatis izinkan semua tool)",
                PermissionMode::ReadOnly => "ReadOnly (Tolak semua aksi mutasi/shell)",
            };
            println!("\nStatus Permission Mode saat ini: {}\n", current_str);

            let options = vec![
                "Ask - Selalu minta konfirmasi untuk shell / write / edit",
                "AutoApprove - Eksekusi otomatis tanpa konfirmasi (seperti unattended agent)",
                "ReadOnly - Blokir semua eksekusi shell dan modifikasi berkas",
                "Batal / Tidak berubah",
            ];

            match Select::new("Pilih Permission Mode baru:", options).prompt() {
                Ok(selected) => {
                    if selected.starts_with("Ask") {
                        permission_gate.mode = PermissionMode::Ask;
                        println!("✔ Permission Mode disetel ke: Ask\n");
                    } else if selected.starts_with("AutoApprove") {
                        permission_gate.mode = PermissionMode::AutoApprove;
                        println!("✔ Permission Mode disetel ke: AutoApprove\n");
                    } else if selected.starts_with("ReadOnly") {
                        permission_gate.mode = PermissionMode::ReadOnly;
                        println!("✔ Permission Mode disetel ke: ReadOnly\n");
                    }
                }
                _ => println!("Mode tetap.\n"),
            }
            true
        }
        "/memory" => {
            match MemoryManager::load_long_term_memory() {
                Some(mem) => {
                    println!("\n══════════════════════════════════════════════════════════════");
                    println!(" 🧠 Workspace Long-Term Memory (.ctrl/MEMORY.md)");
                    println!("══════════════════════════════════════════════════════════════");
                    println!("{}", mem);
                    println!("══════════════════════════════════════════════════════════════\n");
                }
                None => {
                    println!("\nBelum ada catatan memori yang tersimpan di .ctrl/MEMORY.md.\nAI Agent akan otomatis mencatat file dan keputusan penting ke sini.\n");
                }
            }
            true
        }
        "/reset" | "/clear-history" => {
            conversation.clear();
            let _ = MemoryManager::clear_session_history();
            println!("\n✔ Riwayat percakapan & memori sesi berhasil dikosongkan. Konteks baru dimulai!\n");
            true
        }
        "/save" | "/write" => {
            if let Some(content) = &tracker.last_content {
                let target_file = if parts.len() > 1 {
                    parts[1..].join(" ")
                } else if let Some(detected) = detect_filename(content) {
                    println!("\nNama file terdeteksi dari respon: {}", detected);
                    detected
                } else {
                    let default_name = "output.txt".to_string();
                    match Text::new("Masukkan nama file tujuan:").with_default(&default_name).prompt() {
                        Ok(val) => val,
                        Err(_) => return true,
                    }
                };

                match save_code_to_file(&target_file, content) {
                    Ok(summary) => println!("\n💾 Berhasil disimpan ke: {}\n", summary),
                    Err(e) => println!("\n❌ Gagal menyimpan file: {}\n", e),
                }
            } else {
                println!("\nBelum ada respon kode yang bisa disimpan di sesi ini.\n");
            }
            true
        }
        "/tokens" | "/usage" | "/context" => {
            if parts.len() > 1 {
                let sub = parts[1].to_lowercase();
                match sub.as_str() {
                    "toggle" => {
                        user_profile.show_token_usage = !user_profile.show_token_usage;
                        save_user_profile(user_profile);
                        println!(
                            "\n✔ Ringkasan token otomatis: {}\n",
                            if user_profile.show_token_usage {
                                "AKTIF (ditampilkan setelah setiap respon)"
                            } else {
                                "NONAKTIF (disembunyikan)"
                            }
                        );
                    }
                    "on" | "enable" | "true" => {
                        user_profile.show_token_usage = true;
                        save_user_profile(user_profile);
                        println!("\n✔ Ringkasan token otomatis: AKTIF\n");
                    }
                    "off" | "disable" | "false" => {
                        user_profile.show_token_usage = false;
                        save_user_profile(user_profile);
                        println!("\n✔ Ringkasan token otomatis: NONAKTIF\n");
                    }
                    _ => {
                        println!("\nSubcommand token tidak dikenal. Opsi: `/tokens`, `/tokens toggle`, `/tokens on`, `/tokens off`\n");
                    }
                }
            } else {
                print_token_stats(tracker, current_model, user_profile.show_token_usage);
            }
            true
        }
        "/model" => {
            if parts.len() > 1 {
                let new_model = parts[1..].join(" ");
                *current_model = new_model;
                println!("\n✔ Active model switched to: {}\n", current_model);
            } else {
                let options = vec![
                    "glm-5.3-flash (OpenAgentic / Zhipu)",
                    "glm-4-plus (OpenAgentic / Zhipu)",
                    "deepseek-chat (DeepSeek V3)",
                    "deepseek-reasoner (DeepSeek R1)",
                    "llama-3.3-70b-versatile (Groq)",
                    "qwen-2.5-coder-32b (Groq)",
                    "gpt-4o-mini (OpenAI)",
                    "gpt-4o (OpenAI)",
                    "anthropic/claude-3.5-sonnet (OpenRouter)",
                    "Batal / Cancel",
                ];
                match Select::new("Pilih model yang ingin digunakan (gunakan panah ↑/↓):", options).prompt() {
                    Ok(selected) if !selected.starts_with("Batal") => {
                        let model_name = selected.split_whitespace().next().unwrap_or("").to_string();
                        *current_model = model_name;
                        println!("\n✔ Active model switched to: {}\n", current_model);
                    }
                    _ => {
                        println!("\nModel tetap: {}\n", current_model);
                    }
                }
            }
            true
        }
        "/models" => {
            handle_slash_command("/model", current_model, active_skill, user_profile, base_url, tracker, permission_gate, conversation)
        }
        "/skill" | "/skills" => {
            if parts.len() > 1 && cmd == "/skill" {
                let target = parts[1].to_lowercase();
                if target == "reset" || target == "none" || target == "default" {
                    *active_skill = None;
                    println!("\n✔ Skill dinonaktifkan (kembali ke General Assistant).\n");
                } else if let Some(found) = get_available_skills().into_iter().find(|s| s.id == target) {
                    println!("\n✔ Skill aktif: {} ({})\n", found.name, found.id);
                    *active_skill = Some(found);
                } else {
                    println!("\nSkill '{}' tidak ditemukan. Ketik `/skill` untuk memilih dari daftar.\n", parts[1]);
                }
            } else {
                let mut options: Vec<String> = get_available_skills()
                    .iter()
                    .map(|s| format!("{} ({}) - {}", s.name, s.id, s.description))
                    .collect();
                options.push("🔄 reset - Kembali ke General Assistant".to_string());
                options.push("❌ Batal / Cancel".to_string());

                match Select::new("Pilih Skill untuk AI Agent (gunakan panah ↑/↓):", options).prompt() {
                    Ok(selected) if !selected.starts_with("❌") => {
                        if selected.contains("reset") {
                            *active_skill = None;
                            println!("\n✔ Skill dinonaktifkan (kembali ke General Assistant).\n");
                        } else if let Some(id) = selected.split('(').nth(1).and_then(|s| s.split(')').next()) {
                            if let Some(found) = get_available_skills().into_iter().find(|s| s.id == id) {
                                println!("\n✔ Skill aktif: {} ({})\n", found.name, found.id);
                                *active_skill = Some(found);
                            }
                        }
                    }
                    _ => {
                        if let Some(s) = active_skill {
                            println!("\nSkill tetap: {}\n", s.name);
                        } else {
                            println!("\nTetap di mode General Assistant.\n");
                        }
                    }
                }
            }
            true
        }
        "/dev" | "/developer" | "/author" | "/about" => {
            println!("\n══════════════════════════════════════════════════════════════");
            println!(" 💻 About the Developer & Project");
            println!("══════════════════════════════════════════════════════════════");
            println!("  • Creator / Dev  : galangfjr");
            println!("  • Tech Stack     : Python, TypeScript, Rust, Zig");
            println!("  • Project        : ctrl-cli (Ultra-lightweight AI Coding Agent)");
            println!("  • Architecture   : Pure Rust (UCRT64 GNU), LTO Optimized (~1.8 MB)");
            println!("  • Tools Engine   : Unix-style autonomous tool runner (inspired by fx)");
            println!("══════════════════════════════════════════════════════════════\n");
            true
        }
        "/profile" => {
            println!("\n══════════════════════════════════════════════════════════════");
            println!(" 👤 Developer Profile");
            println!("══════════════════════════════════════════════════════════════");
            println!("  • Nama Panggilan : {}", user_profile.name);
            println!("  • Tech Stack     : {}", user_profile.tech_stack.join(", "));
            println!("  • Bahasa Respon  : {}", user_profile.response_language);
            println!("  • Gaya Coding    : {}", user_profile.coding_style);
            println!("══════════════════════════════════════════════════════════════\n");
            true
        }
        "/info" | "/config" => {
            let ctx_info = get_model_context_info(current_model);
            let perm_str = match permission_gate.mode {
                PermissionMode::Ask => "Ask",
                PermissionMode::AutoApprove => "AutoApprove",
                PermissionMode::ReadOnly => "ReadOnly",
            };
            println!("\nActive Session Configuration:");
            println!("  • Endpoint:       {}", base_url);
            println!("  • Active Model:   {} ({})", current_model, ctx_info.note);
            println!("  • Context Window: {} tokens", format_number(ctx_info.context_window));
            if let Some(mo) = ctx_info.max_output {
                println!("  • Max Output:     {} tokens", format_number(mo));
            }
            println!(
                "  • Active Skill:   {}",
                active_skill.as_ref().map(|s| s.name).unwrap_or("None (General Assistant)")
            );
            println!("  • Permission:     {}", perm_str);
            println!("  • History Turns:  {} messages in context", conversation.len());
            println!("  • Developer:      {} (Stack: {})", user_profile.name, user_profile.tech_stack.join(", "));
            println!("  • Token Badge:    {}", if user_profile.show_token_usage { "Aktif (otomatis)" } else { "Nonaktif" });
            println!("  • Session Tokens: {} total ({} queries)", format_number(tracker.total_tokens), tracker.query_count);
            println!("  • API Key:        Loaded (masked)");
            println!();
            true
        }
        "/clear" => {
            print!("\x1B[2J\x1B[1;1H");
            let _ = std::io::stdout().flush();
            true
        }
        "/exit" | "/quit" => false,
        _ => {
            println!("\nUnknown command '{}'. Type /help for available commands.\n", parts[0]);
            true
        }
    }
}

fn start_repl(user_profile: &mut UserProfile) -> Result<()> {
    let (api_key, base_url, default_model) = get_config().unwrap_or((
        String::new(),
        "https://api.openai.com/v1".to_string(),
        "gpt-4o-mini".to_string(),
    ));
    let mut current_model = default_model;
    let mut active_skill: Option<Skill> = None;
    let mut token_tracker = SessionTokenTracker::default();
    let mut conversation: Vec<ChatMessage> = MemoryManager::load_session_history().unwrap_or_default();
    let mut permission_gate = PermissionGate::default();

    println!("══════════════════════════════════════════════════════════════");
    println!(" 🤖 ctrl-cli v0.2.0 (Autonomous AI Coding Agent)");
    println!(" 👋 Created by: galangfjr | Stack: Python, TS, Rust, Zig");
    println!(" Active Model: {}", current_model);
    println!(" Active Skill: General Assistant");
    println!(" Mode: Autonomous Agent with 10 Built-in Tools & Memory");
    if !conversation.is_empty() {
        println!(" 🧠 [Memory] Sesi sebelumnya dipulihkan: {} pesan tersimpan di .ctrl/session.json", conversation.len());
    }
    println!(" Type your prompt and press Enter.");
    println!(" Ketik `/` untuk rekomendasi perintah (/tools, /permissions, /memory, dll.).");
    println!("══════════════════════════════════════════════════════════════\n");

    let is_term = std::io::stdin().is_terminal();

    loop {
        let prompt_label = if let Some(skill) = &active_skill {
            format!("[{} | {}] ➜ ", current_model, skill.id)
        } else {
            format!("[{}] ➜ ", current_model)
        };

        let input_line = if is_term {
            let answer = Text::new(&prompt_label)
                .with_autocomplete(SlashCompleter)
                .prompt();

            match answer {
                Ok(line) => line,
                Err(InquireError::OperationCanceled) | Err(InquireError::OperationInterrupted) => {
                    println!("\nExiting REPL. Goodbye {}!", user_profile.name);
                    break;
                }
                Err(err) => {
                    eprintln!("Input error: {}", err);
                    break;
                }
            }
        } else {
            print!("{}", prompt_label);
            let _ = std::io::stdout().flush();
            let mut line = String::new();
            if std::io::stdin().read_line(&mut line).unwrap_or(0) == 0 {
                break;
            }
            line
        };

        let trimmed = input_line.trim();
        if trimmed.is_empty() {
            continue;
        }

        if trimmed.starts_with('/') {
            if !handle_slash_command(
                trimmed,
                &mut current_model,
                &mut active_skill,
                user_profile,
                &base_url,
                &token_tracker,
                &mut permission_gate,
                &mut conversation,
            ) {
                println!("\nExiting REPL. Goodbye {}!", user_profile.name);
                break;
            }
            continue;
        }

        let system_prompt = build_system_prompt(active_skill.as_ref(), user_profile);

        match run_agent_loop(
            trimmed,
            &mut conversation,
            &current_model,
            &api_key,
            &base_url,
            &mut permission_gate,
            &system_prompt,
            25,
        ) {
            Ok(turn_res) => {
                token_tracker.record(Some(&turn_res.total_usage), &current_model, &turn_res.final_content);
                println!("\n{}\n", turn_res.final_content);

                // Auto-Writer Safety Net: If code was generated but model didn't call write_file
                if let Some(note) = auto_save_if_code_generated(trimmed, &turn_res.final_content, turn_res.tools_executed) {
                    println!("{}", note);
                }

                // Persist session conversation history
                let _ = MemoryManager::save_session_history(&conversation);

                if user_profile.show_token_usage {
                    println!("{}\n", format_token_badge(Some(&turn_res.total_usage), &current_model));
                }
            }
            Err(e) => eprintln!("\n❌ Agent Error: {}\n", e),
        }
    }
    Ok(())
}
