use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use inquire::autocompletion::{Autocomplete, Replacement};
use inquire::error::CustomUserError;
use inquire::{InquireError, Select, Text};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::io::{IsTerminal, Write};
use std::path::PathBuf;

/// Simple Rust CLI harness for AI code generation.
#[derive(Parser)]
#[command(name = "ctrl-cli")]
#[command(author = "Generated by Antigravity")]
#[command(version = "0.1.0")]
#[command(about = "Interactive REPL and generate subcommand for code snippets", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate code snippet from a prompt.
    Generate {
        /// Model name override (e.g. glm-5.3-flash, deepseek-chat, gpt-4o-mini).
        #[arg(short, long)]
        model: Option<String>,

        /// Skill to activate for generation (e.g. rust-expert, code-reviewer, web-frontend).
        #[arg(short, long)]
        skill: Option<String>,

        /// Prompt to send to the AI code generation provider.
        #[arg(num_args = 1.., required = true)]
        prompt: Vec<String>,
    },
}

#[derive(Serialize, Deserialize, Clone, Debug)]
struct UserProfile {
    name: String,
    tech_stack: Vec<String>,
    response_language: String,
    coding_style: String,
}

impl Default for UserProfile {
    fn default() -> Self {
        Self {
            name: "galangfjr".to_string(),
            tech_stack: vec![
                "Python".to_string(),
                "TypeScript".to_string(),
                "Rust".to_string(),
                "Zig".to_string(),
            ],
            response_language: "Bahasa Indonesia".to_string(),
            coding_style: "Tulis kode yang bersih (clean code), modern, idiomatik, efisien, dan minim dependensi tidak perlu. Berikan penjelasan ringkas dan solutif.".to_string(),
        }
    }
}

fn load_user_profile() -> UserProfile {
    let home = std::env::var_os("USERPROFILE")
        .or_else(|| std::env::var_os("HOME"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    let profile_dir = home.join(".ctrl-cli");
    let profile_path = profile_dir.join("profile.json");

    if profile_path.exists() {
        if let Ok(data) = std::fs::read_to_string(&profile_path) {
            if let Ok(prof) = serde_json::from_str::<UserProfile>(&data) {
                return prof;
            }
        }
    }

    let default_profile = UserProfile::default();
    if std::fs::create_dir_all(&profile_dir).is_ok() {
        if let Ok(json_str) = serde_json::to_string_pretty(&default_profile) {
            let _ = std::fs::write(&profile_path, json_str);
        }
    }
    default_profile
}

#[derive(Clone)]
struct Skill {
    id: &'static str,
    name: &'static str,
    description: &'static str,
    system_prompt: &'static str,
}

fn get_available_skills() -> Vec<Skill> {
    vec![
        Skill {
            id: "rust-expert",
            name: "🦀 Rust Expert",
            description: "Spesialis Rust idiomatik, borrow checker, & performa tinggi",
            system_prompt: "You are an elite Rust systems programming expert. Write idiomatic, memory-safe, and high-performance Rust code. Master the borrow checker, use zero-cost abstractions, prefer Result/Option error handling, and explain safety invariants clearly.",
        },
        Skill {
            id: "code-reviewer",
            name: "🔍 Code Reviewer",
            description: "Audit kode menyeluruh untuk bug, celah keamanan, & code smells",
            system_prompt: "You are a senior principal engineer and code reviewer. Rigorously review code for logical bugs, potential memory leaks, security vulnerabilities, edge cases, and maintainability issues. Provide constructive feedback with corrected, refactored code.",
        },
        Skill {
            id: "web-frontend",
            name: "🎨 Web Frontend UI/UX",
            description: "Desain antarmuka modern, HTML/CSS/Tailwind responsif & estetik",
            system_prompt: "You are a modern frontend architect and UI/UX designer. Create visually aesthetic, accessible, modern, and responsive user interfaces using modern HTML, CSS, Tailwind, or component frameworks with clean layouts.",
        },
        Skill {
            id: "api-architect",
            name: "🏗️ API & Backend Architect",
            description: "Desain REST/GraphQL API, skema database, dan autentikasi",
            system_prompt: "You are an enterprise backend and API architect. Design clean, scalable, RESTful or GraphQL APIs with robust validation, secure authentication (JWT/OAuth), clear error response schemas, and efficient database modeling.",
        },
        Skill {
            id: "security-auditor",
            name: "🛡️ Security Auditor",
            description: "Audit keamanan aplikasi (OWASP Top 10, sanitasi input, mitigasi exploit)",
            system_prompt: "You are an application security specialist. Identify security vulnerabilities adhering to OWASP Top 10 guidelines (e.g. injection, broken auth, XSS, SSRF). Explain attack vectors and provide hardened, secure code patches.",
        },
        Skill {
            id: "debugger",
            name: "🐞 Debugger & Trace Doctor",
            description: "Analisis error, stack trace, dan pemecahan masalah sistematis",
            system_prompt: "You are a master software debugger. Analyze stack traces, runtime errors, and unexpected behavior systematically. Perform root-cause analysis, explain why the bug happens, and provide the exact minimal fix.",
        },
        Skill {
            id: "test-engineer",
            name: "🧪 Test Engineer & TDD",
            description: "Pembuatan unit test, integration test, mock, dan edge cases",
            system_prompt: "You are a test-driven development (TDD) engineer. Write comprehensive unit and integration test suites covering edge cases, boundary conditions, error paths, and mocks to ensure 100% reliability.",
        },
        Skill {
            id: "refactor",
            name: "🧹 Clean Code & Refactoring",
            description: "Pembersihan kode, prinsip SOLID/DRY, dan arsitektur modular",
            system_prompt: "You are a software craftsperson focused on clean code, SOLID principles, and DRY architecture. Refactor tangled or bloated code into elegant, modular, and readable components without breaking functionality.",
        },
    ]
}

#[derive(Deserialize, Debug)]
struct ChatResponse {
    choices: Option<Vec<Choice>>,
    error: Option<ApiErrorDetail>,
}

#[allow(dead_code)]
#[derive(Deserialize, Debug)]
struct ApiErrorDetail {
    message: Option<String>,
    code: Option<serde_json::Value>,
}

#[derive(Deserialize, Debug)]
struct Choice {
    message: Option<ChatMessage>,
    text: Option<String>,
}

#[derive(Deserialize, Debug)]
struct ChatMessage {
    content: Option<String>,
    reasoning_content: Option<String>,
}

/// Autocomplete provider for slash commands, models, and skills.
#[derive(Clone, Default)]
struct SlashCompleter;

impl Autocomplete for SlashCompleter {
    fn get_suggestions(&mut self, input: &str) -> Result<Vec<String>, CustomUserError> {
        let mut suggestions = Vec::new();
        if input.starts_with("/model ") {
            let prefix = &input["/model ".len()..];
            let models = [
                "glm-5.3-flash",
                "glm-4-plus",
                "deepseek-chat",
                "deepseek-reasoner",
                "llama-3.3-70b-versatile",
                "qwen-2.5-coder-32b",
                "gpt-4o-mini",
                "gpt-4o",
                "anthropic/claude-3.5-sonnet",
            ];
            for m in models {
                if m.to_lowercase().starts_with(&prefix.to_lowercase()) {
                    suggestions.push(format!("/model {}", m));
                }
            }
        } else if input.starts_with("/skill ") {
            let prefix = &input["/skill ".len()..];
            let mut skill_ids: Vec<&str> = get_available_skills().iter().map(|s| s.id).collect();
            skill_ids.push("reset");
            for id in skill_ids {
                if id.to_lowercase().starts_with(&prefix.to_lowercase()) {
                    suggestions.push(format!("/skill {}", id));
                }
            }
        } else if input.starts_with('/') {
            let commands = [
                "/model",
                "/skill",
                "/dev",
                "/profile",
                "/info",
                "/clear",
                "/help",
                "/exit",
            ];
            for cmd in commands {
                if cmd.starts_with(input) {
                    suggestions.push(cmd.to_string());
                }
            }
        }
        Ok(suggestions)
    }

    fn get_completion(
        &mut self,
        _input: &str,
        highlighted_suggestion: Option<String>,
    ) -> Result<Replacement, CustomUserError> {
        Ok(Replacement::Some(highlighted_suggestion.unwrap_or_default()))
    }
}

fn main() -> Result<()> {
    load_env_file();
    let profile = load_user_profile();
    let cli = Cli::parse();

    match cli.command {
        Some(Commands::Generate { model, skill, prompt }) => {
            let full_prompt = prompt.join(" ");
            let skill_obj = skill.and_then(|s_name| {
                get_available_skills()
                    .into_iter()
                    .find(|s| s.id.eq_ignore_ascii_case(&s_name))
            });
            handle_generate(&full_prompt, model.as_deref(), skill_obj.as_ref(), &profile)?;
        }
        None => {
            // No subcommand -> start REPL.
            start_repl(&profile)?;
        }
    }
    Ok(())
}

/// Automatically loads .env file from common search locations.
fn load_env_file() {
    let mut candidates = Vec::new();
    if let Ok(curr) = std::env::current_dir() {
        candidates.push(curr.join(".env"));
    }
    candidates.push(PathBuf::from(r"C:\Users\Administrator\code-agent-rust\ctrl-cli\.env"));

    for candidate in candidates {
        if candidate.exists() {
            if let Ok(content) = std::fs::read_to_string(&candidate) {
                for line in content.lines() {
                    let trimmed = line.trim();
                    if trimmed.is_empty() || trimmed.starts_with('#') {
                        continue;
                    }
                    if let Some((k, v)) = trimmed.split_once('=') {
                        let key = k.trim();
                        let mut val = v.trim();
                        if (val.starts_with('"') && val.ends_with('"'))
                            || (val.starts_with('\'') && val.ends_with('\''))
                        {
                            if val.len() >= 2 {
                                val = &val[1..val.len() - 1];
                            }
                        }
                        if std::env::var(key).is_err() {
                            std::env::set_var(key, val);
                        }
                    }
                }
            }
            break;
        }
    }
}

/// Retrieves AI configuration from environment variables or .env file.
fn get_config() -> Result<(String, String, String)> {
    let api_key = std::env::var("AI_API_KEY").unwrap_or_default();
    if api_key.is_empty() || api_key == "your_api_key_here" {
        anyhow::bail!(
            "AI_API_KEY is not set!\n\
             Please add your API key in either:\n  \
             • File: C:\\Users\\Administrator\\code-agent-rust\\ctrl-cli\\.env\n  \
             • Terminal: $env:AI_API_KEY=\"your_api_key_here\""
        );
    }
    let base_url = std::env::var("AI_BASE_URL")
        .unwrap_or_else(|_| "https://api.openai.com/v1".to_string());
    let model = std::env::var("AI_MODEL")
        .unwrap_or_else(|_| "gpt-4o-mini".to_string());
    Ok((api_key, base_url, model))
}

/// Handles the `generate` subcommand.
fn handle_generate(
    prompt: &str,
    model_override: Option<&str>,
    active_skill: Option<&Skill>,
    user_profile: &UserProfile,
) -> Result<()> {
    let output = invoke_provider(prompt, model_override, active_skill, user_profile)?;
    println!("{}", output);
    Ok(())
}

/// Handles REPL slash commands like `/model`, `/skill`, `/profile`, `/help`, etc.
/// Returns true if REPL should continue, false if it should exit.
fn handle_slash_command(
    input: &str,
    current_model: &mut String,
    active_skill: &mut Option<Skill>,
    user_profile: &UserProfile,
    base_url: &str,
) -> bool {
    let trimmed = input.trim();
    if trimmed == "/" {
        let options = vec![
            "/model   - Ganti model AI aktif (pilih dari daftar)",
            "/skill   - Pilih / ganti Skill spesialis AI",
            "/dev     - Tentang pembuat / pengembang (galangfjr)",
            "/profile - Lihat Developer Profile aktif",
            "/info    - Cek konfigurasi endpoint & model",
            "/clear   - Bersihkan layar terminal",
            "/help    - Tampilkan bantuan perintah",
            "/exit    - Keluar dari REPL",
        ];
        match Select::new("Pilih perintah [/]:", options).prompt() {
            Ok(choice) => {
                let cmd = choice.split_whitespace().next().unwrap_or("");
                return handle_slash_command(cmd, current_model, active_skill, user_profile, base_url);
            }
            _ => return true,
        }
    }

    let parts: Vec<&str> = trimmed.split_whitespace().collect();
    let cmd = parts[0].to_lowercase();

    match cmd.as_str() {
        "/help" => {
            println!("\nAvailable Slash Commands:");
            println!("  /                   - Buka menu interaktif (panah ↑/↓)");
            println!("  /model              - Pilih model dari menu daftar (panah ↑/↓)");
            println!("  /model <name>       - Ganti langsung ke model tertentu");
            println!("  /skill              - Lihat daftar & pilih skill spesialis (panah ↑/↓)");
            println!("  /skill <name>       - Aktifkan skill tertentu (misal: /skill rust-expert)");
            println!("  /skill reset        - Nonaktifkan skill (kembali ke General Assistant)");
            println!("  /dev                - Info pembuat / pengembang aplikasi ({})", user_profile.name);
            println!("  /profile            - Lihat Developer Profile Anda ({})", user_profile.name);
            println!("  /info, /config      - Tampilkan endpoint & konfigurasi sesi");
            println!("  /clear              - Bersihkan layar");
            println!("  /exit, /quit        - Keluar dari REPL");
            println!("  /help               - Bantuan ini\n");
            true
        }
        "/model" => {
            if parts.len() > 1 {
                let new_model = parts[1..].join(" ");
                *current_model = new_model;
                println!("\n✔ Active model switched to: {}\n", current_model);
            } else {
                let options = vec![
                    "glm-5.3-flash (OpenAgentic / Zhipu)",
                    "glm-4-plus (OpenAgentic / Zhipu)",
                    "deepseek-chat (DeepSeek V3)",
                    "deepseek-reasoner (DeepSeek R1)",
                    "llama-3.3-70b-versatile (Groq)",
                    "qwen-2.5-coder-32b (Groq)",
                    "gpt-4o-mini (OpenAI)",
                    "gpt-4o (OpenAI)",
                    "anthropic/claude-3.5-sonnet (OpenRouter)",
                    "Batal / Cancel",
                ];
                match Select::new("Pilih model yang ingin digunakan (gunakan panah ↑/↓):", options).prompt() {
                    Ok(selected) if !selected.starts_with("Batal") => {
                        let model_name = selected.split_whitespace().next().unwrap_or("").to_string();
                        *current_model = model_name;
                        println!("\n✔ Active model switched to: {}\n", current_model);
                    }
                    _ => {
                        println!("\nModel tetap: {}\n", current_model);
                    }
                }
            }
            true
        }
        "/models" => {
            handle_slash_command("/model", current_model, active_skill, user_profile, base_url)
        }
        "/skill" | "/skills" => {
            if parts.len() > 1 && cmd == "/skill" {
                let target = parts[1].to_lowercase();
                if target == "reset" || target == "none" || target == "default" {
                    *active_skill = None;
                    println!("\n✔ Skill dinonaktifkan (kembali ke General Assistant).\n");
                } else if let Some(found) = get_available_skills().into_iter().find(|s| s.id == target) {
                    println!("\n✔ Skill aktif: {} ({})\n", found.name, found.id);
                    *active_skill = Some(found);
                } else {
                    println!("\nSkill '{}' tidak ditemukan. Ketik `/skill` untuk memilih dari daftar.\n", parts[1]);
                }
            } else {
                let mut options: Vec<String> = get_available_skills()
                    .iter()
                    .map(|s| format!("{} ({}) - {}", s.name, s.id, s.description))
                    .collect();
                options.push("🔄 reset - Kembali ke General Assistant".to_string());
                options.push("❌ Batal / Cancel".to_string());

                match Select::new("Pilih Skill untuk AI Agent (gunakan panah ↑/↓):", options).prompt() {
                    Ok(selected) if !selected.starts_with("❌") => {
                        if selected.contains("reset") {
                            *active_skill = None;
                            println!("\n✔ Skill dinonaktifkan (kembali ke General Assistant).\n");
                        } else if let Some(id) = selected.split('(').nth(1).and_then(|s| s.split(')').next()) {
                            if let Some(found) = get_available_skills().into_iter().find(|s| s.id == id) {
                                println!("\n✔ Skill aktif: {} ({})\n", found.name, found.id);
                                *active_skill = Some(found);
                            }
                        }
                    }
                    _ => {
                        if let Some(s) = active_skill {
                            println!("\nSkill tetap: {}\n", s.name);
                        } else {
                            println!("\nTetap di mode General Assistant.\n");
                        }
                    }
                }
            }
            true
        }
        "/dev" | "/developer" | "/author" | "/about" => {
            println!("\n══════════════════════════════════════════════════════════════");
            println!(" 💻 About the Developer & Project");
            println!("══════════════════════════════════════════════════════════════");
            println!("  • Creator / Dev  : galangfjr");
            println!("  • Tech Stack     : Python, TypeScript, Rust, Zig");
            println!("  • Project        : ctrl-cli (Ultra-lightweight AI Coding Agent)");
            println!("  • Architecture   : Pure Rust (UCRT64 GNU), LTO Optimized (~1.8 MB)");
            println!("  • Vision         : Minimal resource usage coding agent harness");
            println!("══════════════════════════════════════════════════════════════\n");
            true
        }
        "/profile" => {
            println!("\n══════════════════════════════════════════════════════════════");
            println!(" 👤 Developer Profile");
            println!("══════════════════════════════════════════════════════════════");
            println!("  • Nama Panggilan : {}", user_profile.name);
            println!("  • Tech Stack     : {}", user_profile.tech_stack.join(", "));
            println!("  • Bahasa Respon  : {}", user_profile.response_language);
            println!("  • Gaya Coding    : {}", user_profile.coding_style);
            println!("══════════════════════════════════════════════════════════════\n");
            true
        }
        "/info" | "/config" => {
            println!("\nActive Session Configuration:");
            println!("  • Endpoint:      {}", base_url);
            println!("  • Active Model:  {}", current_model);
            println!(
                "  • Active Skill:  {}",
                active_skill.as_ref().map(|s| s.name).unwrap_or("None (General Assistant)")
            );
            println!("  • Developer:     {} (Stack: {})", user_profile.name, user_profile.tech_stack.join(", "));
            println!("  • API Key:       Loaded (masked)");
            println!();
            true
        }
        "/clear" => {
            print!("\x1B[2J\x1B[1;1H");
            let _ = std::io::stdout().flush();
            true
        }
        "/exit" | "/quit" => false,
        _ => {
            println!("\nUnknown command '{}'. Type /help for available commands.\n", parts[0]);
            true
        }
    }
}

/// Starts an interactive REPL where each line is sent to the provider.
fn start_repl(user_profile: &UserProfile) -> Result<()> {
    let (_, base_url, default_model) = get_config().unwrap_or((
        String::new(),
        "https://api.openai.com/v1".to_string(),
        "gpt-4o-mini".to_string(),
    ));
    let mut current_model = default_model;
    let mut active_skill: Option<Skill> = None;

    println!("══════════════════════════════════════════════════════════════");
    println!(" 🤖 ctrl-cli REPL (AI Coding Agent)");
    println!(" 👋 Created by: galangfjr | Stack: Python, TS, Rust, Zig");
    println!(" Active Model: {}", current_model);
    println!(" Active Skill: General Assistant");
    println!(" Type your prompt and press Enter.");
    println!(" Ketik `/` untuk rekomendasi interaktif (geser panah ↑ / ↓).");
    println!(" Commands: /model, /skill, /dev, /profile, /info, /clear, /help, /exit");
    println!("══════════════════════════════════════════════════════════════\n");

    let is_term = std::io::stdin().is_terminal();

    loop {
        let prompt_label = if let Some(skill) = &active_skill {
            format!("[{} | {}] ➜ ", current_model, skill.id)
        } else {
            format!("[{}] ➜ ", current_model)
        };

        let input_line = if is_term {
            let answer = Text::new(&prompt_label)
                .with_autocomplete(SlashCompleter)
                .prompt();

            match answer {
                Ok(line) => line,
                Err(InquireError::OperationCanceled) | Err(InquireError::OperationInterrupted) => {
                    println!("\nExiting REPL. Goodbye {}!", user_profile.name);
                    break;
                }
                Err(err) => {
                    eprintln!("Input error: {}", err);
                    break;
                }
            }
        } else {
            // Piped input fallback
            print!("{}", prompt_label);
            let _ = std::io::stdout().flush();
            let mut line = String::new();
            if std::io::stdin().read_line(&mut line).unwrap_or(0) == 0 {
                break;
            }
            line
        };

        let trimmed = input_line.trim();
        if trimmed.is_empty() {
            continue;
        }

        if trimmed.starts_with('/') {
            if !handle_slash_command(trimmed, &mut current_model, &mut active_skill, user_profile, &base_url) {
                println!("\nExiting REPL. Goodbye {}!", user_profile.name);
                break;
            }
            continue;
        }

        match invoke_provider(trimmed, Some(&current_model), active_skill.as_ref(), user_profile) {
            Ok(res) => println!("\n{}\n", res),
            Err(e) => eprintln!("\nError: {}\n", e),
        }
    }
    Ok(())
}

/// Extracts a JSON object substring by finding the first '{' and the last '}'.
/// This handles cases where API proxies append trailing text like `data: [DONE]`.
fn extract_json_slice(raw: &str) -> &str {
    let trimmed = raw.trim();
    if let (Some(start), Some(end)) = (trimmed.find('{'), trimmed.rfind('}')) {
        if start <= end {
            return &trimmed[start..=end];
        }
    }
    trimmed
}

/// Invokes the OpenAI-compatible Cloud AI provider with active skill and user profile injection.
fn invoke_provider(
    prompt: &str,
    model_override: Option<&str>,
    active_skill: Option<&Skill>,
    user_profile: &UserProfile,
) -> Result<String> {
    let (api_key, base_url, default_model) = get_config()?;
    let model = model_override.unwrap_or(&default_model);
    let endpoint = format!("{}/chat/completions", base_url.trim_end_matches('/'));

    let default_system = "You are a fast, concise, helpful coding agent CLI tool. Provide direct, high quality code and clear explanations.";
    let skill_part = active_skill.map(|s| s.system_prompt).unwrap_or(default_system);

    let profile_part = format!(
        "\n\n[User Profile: {}]\n- Preferred Tech Stack: {}\n- Response Language: {}\n- Coding Style Guidelines: {}",
        user_profile.name,
        user_profile.tech_stack.join(", "),
        user_profile.response_language,
        user_profile.coding_style
    );

    let full_system = format!("{}{}", skill_part, profile_part);

    let body = json!({
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": full_system
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "temperature": 0.2
    });

    let response = ureq::post(&endpoint)
        .set("Authorization", &format!("Bearer {}", api_key))
        .set("Content-Type", "application/json")
        .timeout(std::time::Duration::from_secs(60))
        .send_json(body);

    match response {
        Ok(res) => {
            let raw_text = res
                .into_string()
                .context("Failed to read response body from AI provider")?;

            let clean_json = extract_json_slice(&raw_text);

            let chat_res: ChatResponse = serde_json::from_str(clean_json)
                .with_context(|| format!("Failed to parse AI provider JSON response: {}", clean_json))?;

            if let Some(err) = chat_res.error {
                let msg = err.message.unwrap_or_else(|| "Unknown API error".to_string());
                anyhow::bail!("AI Provider error: {}", msg);
            }

            let content = chat_res
                .choices
                .as_ref()
                .and_then(|c| c.first())
                .and_then(|c| {
                    c.message
                        .as_ref()
                        .and_then(|m| {
                            m.content
                                .clone()
                                .filter(|s| !s.trim().is_empty())
                                .or_else(|| m.reasoning_content.clone())
                        })
                        .or_else(|| c.text.clone())
                })
                .unwrap_or_else(|| "(empty response)".to_string());

            Ok(content.trim().to_string())
        }
        Err(ureq::Error::Status(code, resp)) => {
            let err_body = resp.into_string().unwrap_or_default();
            anyhow::bail!("AI Provider returned HTTP {}: {}", code, err_body);
        }
        Err(e) => {
            anyhow::bail!("Network request error: {}", e);
        }
    }
}
